### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by xDShot** [Joshua-Ashton/dxup#13]
[xdshot@lenovo-pc dxup]$ export WINEARCH=win64
[xdshot@lenovo-pc dxup]$ export WINEPREFIX=~/.wine64/
[xdshot@lenovo-pc dxup]$ meson --cross-file build-win64.txt -Denable_tests=false bbbuild
The Meson build system
Version: 0.46.0
Source dir: /home/xdshot/dxup
Build dir: /home/xdshot/dxup/bbbuild
Build type: cross build
Project name: dxup
000b:fixme:winediag:start_process Wine Staging 3.8 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
Native C compiler: ccache cc (gcc 8.1.0 "cc (GCC) 8.1.0")
Cross C compiler: /usr/bin/x86_64-w64-mingw32-gcc (gcc 8.1.0)
Native C++ compiler: ccache c++ (gcc 8.1.0 "c++ (GCC) 8.1.0")
Cross C++ compiler: /usr/bin/x86_64-w64-mingw32-g++ (gcc 8.1.0)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library d3d11 found: YES

wine_utils/meson.build:4:0: ERROR:  File setup_dx10to11.sh.in does not exist.

A full log can be found at /home/xdshot/dxup/bbbuild/meson-logs/meson-log.txt

**Comment by xDShot** [comment]
[meson-log.txt](https://github.com/Joshua-Ashton/dxup/files/2017039/meson-log.txt)

**Comment by Joshua-Ashton** [comment]
fixed
