### ISSUE TITLE
Cannot be compiled on Linux

### ISSUE THREAD

**Issue by RomanHargrave** [Joshua-Ashton/dxup#15]
There are a few issues that affect the ability of a linux host to cross-compile DXUP for Windows/Wine

1. [MSVCisms in source code](https://github.com/Joshua-Ashton/dxup/issues/3#issuecomment-386635243)

2. Missing headers (`dxgi1_3.h`)

3. References to nonexistant files in the Meson build

It would be advisable to clarify this in the README until such a time where these are fixed. I ***strongly*** dislike MSVC and Win32 C++ so I may or may not make an effort to repair the issue myself.

**Comment by otaviomad** [comment]
yeah, ran into this while trying to compile. seems like the project is abandoned. I hope the dev comes back bc I have no idea of how to fix it.

**Comment by Joshua-Ashton** [comment]
https://github.com/Joshua-Ashton/dxup/commit/80172043fd6dc46976198d29a21e237104f45dce
