### ISSUE TITLE
no dx10 support?

### ISSUE THREAD

**Issue by Teuwu** [Joshua-Ashton/dxup#17]
I think I did something wrong to be getting this. (obviously)
so wine 3.9 dxvk dlls 0.54 and the version of dxup that was on here today 06/08/2018.
download the dxup-x64.zip, extract, read readme file.
download dxvk-0.54 in the x64 sub folder rename dxgi.dll -> dxgi_original.dll.
copy both d3d11.dll and dxgi_original.dll to dxup-x64 folder.
dos2unix fix the setup script, do the export WINEPREFIX variable.
run setup script.
try to run game, complains dx10 not supported? what what did I do wrong here?
fyi, the game is original crysis x64 version.

**Comment by Joshua-Ashton** [comment]
There's a DXVK environment variable you need to set.
