### ISSUE TITLE
[d3d9-dev] Virtual milestones

### ISSUE THREAD

**Issue by pchome** [Joshua-Ashton/dxup#26]
e.g. https://github.com/koalaylj/hello-directx

Some tests are runs fine using DXVK, but draws nothing, due to missing
* Direct3DDevice9Ex::SetClipPlane
* Direct3DDevice9Ex::SetTransform
* Direct3DDevice9Ex::SetRenderState

[log_d3d9.txt](https://github.com/Joshua-Ashton/dxup/files/2705291/log_d3d9.txt)
[02_Triangle_dxgi.log](https://github.com/Joshua-Ashton/dxup/files/2705292/02_Triangle_dxgi.log)
[02_Triangle_d3d11.log](https://github.com/Joshua-Ashton/dxup/files/2705293/02_Triangle_d3d11.log)

**Comment by Joshua-Ashton** [comment]
The clip plane wouldn't matter and neither would the render state (it would just render wrong with renderstate, and I doubt they're actually setting anything other than a degenerate clip plane.)

These examples are 90% fixed-function. I haven't started work on that yet.

**Comment by pchome** [comment]
I'm not sure if this useful, but here is some WINE test results:
* d3d9-stateblock (finished, 12723 tests executed (0 marked as todo, 1056 failures), 0 skipped.)
  - [d3d9-stateblock.test.log](https://github.com/Joshua-Ashton/dxup/files/2799738/d3d9-stateblock.test.log)
  - [test-d3d9-stateblock_d3d9.log](https://github.com/Joshua-Ashton/dxup/files/2799734/test-d3d9-stateblock_d3d9.log)
* d3d9-visual (failed w/ exception)
  - [d3d9-visual.test.log](https://github.com/Joshua-Ashton/dxup/files/2799737/d3d9-visual.test.log)
  - [test-d3d9-visual_d3d9.log](https://github.com/Joshua-Ashton/dxup/files/2799733/test-d3d9-visual_d3d9.log)
* d3d9-device (failed w/ exception)
  - [d3d9-device.test.log](https://github.com/Joshua-Ashton/dxup/files/2799739/d3d9-device.test.log)
  - [test-d3d9-device_d3d9.log](https://github.com/Joshua-Ashton/dxup/files/2799735/test-d3d9-device_d3d9.log)
* d3d9-d3d9ex (failed w/ exception)
  - [d3d9-d3d9ex.test.log](https://github.com/Joshua-Ashton/dxup/files/2799740/d3d9-d3d9ex.test.log)
  - [test-d3d9-d3d9ex_d3d9.log](https://github.com/Joshua-Ashton/dxup/files/2799736/test-d3d9-d3d9ex_d3d9.log)

Meson build for some d3d* standalone tests : [dx1x-tests](https://github.com/pchome/wine-playground/tree/master/dx1x-tests)

**Comment by pchome** [comment]
Yep, I understand this. ;)
_e.g. "returned 0 instead of ..." because of `return S_OK` stubs, an so on_

Just FYI.
