### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by pchome** [Joshua-Ashton/dxup#27]
In case someone interested in.

VS Code example (`dxup/.vscode/launch.json`):
```json
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Debug",
            "type": "gdb",
            "request": "attach",
            "executable": "/usr/lib/wine-vanilla-3.21/bin/wine",
            "cwd": "${workspaceRoot}",
            "target": ":2345",
            "remote": true,
            "valuesFormatting": "prettyPrinters"
        }
    ]
}
```

* In terminal: `$ winedbg --gdb --no-start --port 2345 Test.exe`
* In VS Code: set breakpoints
* Run debug

Note:
* I'm using `winedbg` from wine-staging, cause wine-vanilla's one refuse to launch for me
* With a test program built as winelib, and dxup winelib build I can walk through both sources during debug (will probably try to install WINE sources as well)

**Comment by Joshua-Ashton** [comment]
This isn't an issue with dxup -- this is more suited for a readme file in your fork.
