### ISSUE TITLE
Build troubles

### ISSUE THREAD

**Issue by SveSop** [Joshua-Ashton/dxup#3]
Interesting project, so i thought i would give it a test... Used the same machine i build dxvk with (just built dxvk without errors prior to testing this).
Ubuntu 18.04 w/mostly ubuntu release packages.

Attaching log after doing the regular meson config (same as i would do with dxvk) and running "ninja"
[build.log](https://github.com/Joshua-Ashton/dxup/files/1964953/build.log)

**Comment by SveSop** [comment]
And meson log from build.w64 folder incase it helps.
[meson-log.txt](https://github.com/Joshua-Ashton/dxup/files/1964969/meson-log.txt)

**Comment by Joshua-Ashton** [comment]
Yeah I need to go through and make mingw building and the likes work. Haven't had an opportunity recently, will do soon though 😄

**Comment by SveSop** [comment]
@Joshua-Ashton And to answer my previous question, i guess it might be a windows VS2017 build? (ref. [https://github.com/Joshua-Ashton/dxup/blob/master/appveyor.yml](https://github.com/Joshua-Ashton/dxup/blob/master/appveyor.yml) )

Maybe change the howto on the README on front page how to build using VS2017 until you fix Linux mingw build? (Ill probably make a wild stab in the dark trying a VS2007 windows build anyway tho, but..)

**Comment by SveSop** [comment]
Bah.. that really turned out to be a stab in the dark indeed.

So.. let me just ask: Is this a source intended to be built by other than you, or just a "personal dump of various source files"? :)

Im asking, cos im a total noob. Sure i can follow instructions, but i find it kinda hard here since its not remotely near working. I mean.. have you tested it yourself, and everything works by doing a git clone to a NEW directory and following your own instructions? :)

`wine_utils/meson.build:4:0: ERROR: File setup_dx10to11.sh.in does not exist.`
Skipping building anything in the wine_utils folder ofc ends up in the same error-filled list as before.

Please explain to me in simple steps how to build.. im eager to test dxup with dxvk to see if i can get some dx10 action :)

PS. `Please don't go messing it up then complaining :( It makes ME sad` (Fun quote from wine_utils/readme.txt)

**Comment by Joshua-Ashton** [comment]
@enrique556 You're overcomplicating it. Ninja is not required and you can just use the meson installer online
Just ``meson build --backend vs2017``

@pchome Looks similar to the changes I made for another project to get working under MinGW. Could you submit a pull request? 😄

**Comment by SveSop** [comment]
@enrique556 Excellent instructions! 
Found that i had to use "x64 Native Tools" to build the x64 dll's, as i got a "wrong architecture" when trying a 64 bit app with it.. Possibly something i missed/did wrong tho, but worked fine with dx11 apps with that.

Tested Unigine Tropics in DX10 mode, but crashed, and i tested "Lost Planet".. also crashed.
Unigine Tropics does not work with wined3d either, so that might be a different issue possibly, but Lost Planet works with regular wine. Will see if i can find something else to test tho.

**Comment by enrique556** [comment]
@SveSop 
Regarding the `x64 Native Tools Command Prompt`: 
I re-tested with the one I suggested and that one, and it didn't make a difference, meson built the sln with 64 bitness correctly, and the compiled dxgi.dll was exactly 18,944 bytes in size for both builds.

re. `unimplemented function DXGI.DLL.CreateDXGIFactory@8 called in 32-bit code`:
I did not get anything like that in the output when I ran crysis warhead. Are Unigine Tropics and Lost Planet x64 apps? ie. are you sure you're using the right wine version and build of the dlls?
The only other thing I can think of mentioning is that you might need wine-staging 3.7 rather than wine 3.7 - at least I did.

**Comment by Joshua-Ashton** [comment]
If you are getting ``unimplemented function DXGI.DLL.CreateDXGIFactory@8 called in 32-bit code`` you arent using the right arch

**Comment by SveSop** [comment]
@Joshua-Ashton The only two compiler "shells" in my vs2017 windows 64bit install that would generate win32(x86) code that will NOT give a "Wrong architecture" error is:
`x86 Native Tools Command Prompt` and `x64_86 Cross Tools Command Prompt` Using those compiled as win32, and give the "unimplemented function" error.
`x64 Native Tools Command Prompt` and `x86_x64 Cross Tools Command Prompt` produce x64 code and give "wrong architecture".

What am i doing wrong?

**Comment by SveSop** [comment]
@enrique556 I am using wine-staging-3.7 in a 64-bit prefix.
32-bit benchmarks like Unigine Valley properly redirects to dxvk 32-bit d3d11.dll, and benchmark runs like it should.
64-bit benchmark like Unigine Superposition properly redirects to dxvk 64-bit d3d11.dll as it should. Before using the x64 Native Tools Command Prompt i got a "wrong architecture" when trying to run Unigine Superposition from the dxup dxgi.dll, and thus no redirecting to dxgi_original.dll i guess.

I have not tested Crysis Warhead nor Just Cause, so i can not replicate a "working condition" that way.. I see there is a "weekend sale" on crysis warhead on steam, but meh.. wont play it anyway, so dunno if i cba to buy it just to test :)

Also tested nVidia "tech-demo" Cascades, but same error there.. Although those "feature tests" tend to not be optimal with wine anyway, as it is more a "only works with x.xx version nvidia driver" and such things... So of the "free things to test" i would guess Unigine Tropics would be the best bet as it has DX9/DX10/DX11 modes to test. DX11 mode works with DXVK with some minor texture glitches tho.

**Comment by enrique556** [comment]
@SveSop Usually the 64 bit executables are marked as such either by being in a separate "bin64" or similarly named folder, or having ExeName64.exe or ExeName_x64.exe kind of suffix.
I think it's safe to say that Unigine Tropics and Lost Planet are both 32 bit, in which case you're just having other troubles, as I was with Crysis 2 and MWO. Unless you want to get yourself a copy of Crysis Warhead or that other game Justin tested, just to see this thing work, then it might be better waiting for next release.
For your sanity, you could compare your built DLL sizes against mine for 32 bit (others included for reference):
**Release, 32bit:**
`d3d10.dll: 11,776 bytes`
`d3d10_1.dll: 64,512 bytes`
`dxgi.dll: 16,384 bytes`
**Release, 64bit:**
`d3d10.dll: 14,336 bytes`
`d3d10_1.dll: 78,336 bytes`
`dxgi.dll: 18,944 bytes`

**Comment by SveSop** [comment]
@enrique556 I know.. And yes, Unigine Valley/Heaven/Tropics are all 32-bit, where Unigine Superposition is 64-bit.

Slight difference for me.. dunno why:
Release, 32bit:
`d3d10.dll: 11,264 bytes`
`d3d10_1.dll: 64,024 bytes`
`dxgi.dll: 16,384 bytes`
Release, 64bit:
`d3d10.dll: 14,848 bytes`
`d3d10_1.dll: 77,824 bytes`
`dxgi.dll: 18,944 bytes`

Any way to check versions of something in vs2017? Some update or whatnot with a different compiler?

**Comment by enrique556** [comment]
@SveSop Yes, in the appropriate command prompt, type `cl`, it'll tell you which compiler version you're at. Here's my 32 bit compiler output:
`Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26428.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.`
.. But I think it's more likely that I'm building an out-of-date copy of the DXUP source. I'll redo tomorrow and see if there's a difference.

Oh BTW (should've remembered this earlier): You can tell the bitness of a linux executable by using the `file` command, eg:
`file <filename>`

**Comment by SveSop** [comment]
@enrique556 Cleared out my local copy and did a fresh git clone.
file x32/d3d10.dll
`d3d10.dll: PE32 executable (DLL) (GUI) Intel 80386, for MS Windows`
file x64/d3d10.dll
`d3d10.dll: PE32+ executable (DLL) (GUI) x86-64, for MS Windows`
However file x32/d3d11.dll (from dxvk compiled with mingw)
`d3d11.dll: PE32 executable (DLL) (console) Intel 80386 (stripped to external PDB), for MS Windows`
file x64/d3d11.dll
`d3d11.dll: PE32+ executable (DLL) (console) x86-64 (stripped to external PDB), for MS Windows`

"Stripped" does not really mean much, but i am not sure if (GUI) vs (console) is relevant?

Other than that, i cant say i have much more ideas than the error message is somewhat correct.. meaning that `unimplemented function DXGI.DLL.CreateDXGIFactory@8` is actually referring to some unimplemented function that Warhead or Just cause dont utilize?

**Comment by SveSop** [comment]
If i run `nVidia Cascades` with wined3d and wine-3.7, i get this from the log:
```
0009:fixme:win:EnumDisplayDevicesW ((null),0,0x33da58,0x00000000), stub!
0009:fixme:win:EnumDisplayDevicesW ((null),0,0x33d9d8,0x00000000), stub!
0009:fixme:win:EnumDisplayDevicesW ((null),0,0x33dcb8,0x00000000), stub!
0009:fixme:win:EnumDisplayDevicesW ((null),0,0x33dc38,0x00000000), stub!
0009:fixme:dxgi:dxgi_factory_MakeWindowAssociation iface 0x150430, window 0x10062, flags 0 stub!
0009:fixme:dxgi:dxgi_swapchain_GetDesc Ignoring ScanlineOrdering, Scaling and SwapEffect.
0009:fixme:d3d10:D3D10ReflectShader data 0x7c3c78, data_size 988, reflector 0x33e2a8 stub!
0009:fixme:d3d10:d3d10_shader_reflection_GetDesc iface 0x165760, desc 0x33e234 stub!
0009:fixme:d3d10:d3d10_shader_reflection_GetConstantBufferByIndex iface 0x165760, index 0 stub!
wine: Unhandled page fault on read access to 0x00000000 at address 0x4b24e2 (thread 0009), starting debugger...

```
I dunno.. is "shader_reflection" something that might crash dxup? :) The "GetConstantBufferByIndex" is something that has been bug reported for Assassins Creed, and not fixed. That does not mean it would not work with dxup tho, cos there are from what i gather several things working with dxvk that does not with wined3d :)

**Comment by pchome** [comment]
@Joshua-Ashton 
> Could you submit a pull request?

You can take this diff as a guide, since I can't check if this ok for VS, and you (obviously) can't check MinGW with gcc. So please accept changes not breaking VS builds manually.

This is the first step for cross-compilation, because even with this patches MinGW builds won't work.

**Comment by enrique556** [comment]
@SveSop I downloaded cascades (good free dx10 test you found there) and it did not work for me either, but noticed the two following lines in output:
`0009:err:module:import_dll Library win32u.dll (which is needed by L"C:\\Program Files\\NVIDIA Corporation\\NVIDIA Demos\\Cascades\\bin\\dxgi_original.dll") not found`
`0009:err:module:import_dll Library api-ms-win-dx-d3dkmt-l1-1-2.dll (which is needed by L"C:\\Program Files\\NVIDIA Corporation\\NVIDIA Demos\\Cascades\\bin\\dxgi_original.dll") not found
`
.. It's blaming dxgi_original (which is the DXVK version of dxgi) for needing these 2 windows dlls.

**Comment by SveSop** [comment]
@enrique556 Well.. wine does not have this .dll, but i found it in the system folders of my Win10 VBOX image.. 

I believe the .dll's - also the dxgi_original.dll and the other dxup dll's should be installed in their respective /windows/system32 (64 bit) and /windows/syswow64 (32 bit) folders rather than put in the same folder as the .exe file you are running. This was explained to some degree on the dxvk issues page a while back, and is what the install script does. Has to do with some system-loading-dll's or whatnot.

**Comment by enrique556** [comment]
@SveSop Yes I found it in my win10 vm also, but it was notably absent from my long-in-the-tooth windows7 drive.

Re: putting the dlls in the system folder(s) rather than the exe folder: I didn't think that'd matter (end users' famous last words). I'll test that today.

**Comment by Joshua-Ashton** [comment]
https://github.com/Joshua-Ashton/dxup/commit/80172043fd6dc46976198d29a21e237104f45dce

**Comment by Joshua-Ashton** [comment]
Closing this as I believe this is fixed (at least in master rn.) LMK if you have any issues.
