### ISSUE TITLE
I can't compile this project :frog:

### ISSUE THREAD

**Issue by Tk-Glitch** [Joshua-Ashton/dxup#32]
Mingw when? :frog: 
Winegcc when? :frog: 
When will it be available in wine-tkg? :frog:

**Comment by Joshua-Ashton** [comment]
When I ship v0.00 and merge d3d9-dev into master, it will compile on mingw and winegcc.

**Comment by Tk-Glitch** [comment]
That answer was too good for the meme. Take all the time you need mate.

**Comment by Joshua-Ashton** [comment]
:frog:
