### ISSUE TITLE
project license?

### ISSUE THREAD

**Issue by kphillisjr** [Joshua-Ashton/dxup#4]
I was looking over the code in the project and noticed no license is mentioned. This is important since it provides a general idea on how the source code is used. Also, Since the goal of this project is similar to what [VK9](https://github.com/disks86/VK9) does for Direct3D 9, and [DXVK](https://github.com/doitsujin/dxvk) does for Direct 3D 11, I would like to suggest using the license both of the projects use which is the [zlib license](https://en.wikipedia.org/wiki/Zlib_License).

**Comment by Joshua-Ashton** [comment]
The project is MIT. I think I just forgot to push the license. Will fix
