### ISSUE TITLE
Add '--always' to vcs_tag in meson.build

### ISSUE THREAD

**Issue by ComfyKernel** [Joshua-Ashton/dxup#48]
Without it there is a chance that the build will fail because git couldn't generate a full version name.

change
```
> ['git', 'describe' '--dirty=+']
```
to
```
> ['git', 'describe', '--always', '--dirty=+']
```

**Comment by Joshua-Ashton** [comment]
Hi, I actually didn't write this, I adapted dxvk's build scripts.

Is there a reason why this only affects dxup and the same doesn't apply to dxvk?
(dxvk: https://github.com/doitsujin/dxvk)

**Comment by ComfyKernel** [comment]
It's possible this also affects DXVK, I just haven't had the need to build it in a long time since it's distributed on steam and in winetricks

**Comment by Joshua-Ashton** [comment]
Looked into this more, added it.
Seems like it's needed when nothing is tagged.

Cheers!
 - Josh
