### ISSUE TITLE
Prebuilt binaries for testing..

### ISSUE THREAD

**Issue by oscarbg** [Joshua-Ashton/dxup#5]
can you provide some prebuilt binaries for testing..
I'm having build issues under linux mingw currently..

**Comment by SveSop** [comment]
@oscarbg That would be nice.
Already posted build issues [https://github.com/Joshua-Ashton/dxup/issues/3](https://github.com/Joshua-Ashton/dxup/issues/3)

**Comment by Joshua-Ashton** [comment]
appveyor

**Comment by oscarbg** [comment]
thanks..
just posting link:
https://ci.appveyor.com/project/Joshua-Ashton/dxup

**Comment by enrique556** [comment]
> thanks..
just posting link:
https://ci.appveyor.com/project/Joshua-Ashton/dxup

LOL, I spent about 5 hours getting this thing to compile locally. This link should be in a prominent spot.

@oscarbg Thanks for pointing this out.

@SveSop prebuilt binaries sitting there - go to jobs, pick x64 or x32, then go to artifacts to get the zip file.

**Comment by SveSop** [comment]
@enrique556 Tested with the prebuilt binaries from the link posted above, and got the same error as my own compiled.. so i guess something else is behind the error.

For ref. [https://github.com/Joshua-Ashton/dxup/issues/3](https://github.com/Joshua-Ashton/dxup/issues/3)
