### ISSUE TITLE
Need better documentation

### ISSUE THREAD

**Issue by iareciog** [Joshua-Ashton/dxup#6]
You need better documentation about what you want to say with "/your/target/directory" and what exactly it uses with dxvk in linux. Because I tried to compile but a meson file it has 1 wrong thing, the file is "wine_utils/meson.build".

It indicates an entry of 'setup_dx10to11.sh.in' and does not exist, but there is "setup_dxup.in". And I changed this, now it compiles, but in Linux at least it does not create the .dll in the directories. And the DLLs that we must copy to wine_utils from dxvk, it is not specified if it should be x86 or x64. Because the Linux script does both and none works.

I hope you can find the best way to make it work.

Sorry if something is bad translated.

**Comment by SveSop** [comment]
@iareciog What linux distro and/or mingw versions and stuff are you using? I am nowhere near compiling the source, but did not try the patches posted in [https://github.com/Joshua-Ashton/dxup/issues/3#issuecomment-386635243](https://github.com/Joshua-Ashton/dxup/issues/3#issuecomment-386635243)

**Comment by iareciog** [comment]
I'm using ArchLinux with Mingw 7.3.0. I should try the patches.

**Comment by SveSop** [comment]
@iareciog Hmm.. i wonder what is the difference between Ubuntu 18.04 and ArchLinux. Also have mingw 7.3.0, but nothing compiles. Probably some minor setting then i would think..

My build log: 
[build.log](https://github.com/Joshua-Ashton/dxup/files/1980071/build.log)

**Comment by Joshua-Ashton** [comment]
Documentation will be improved when I merge d3d9-dev.
