### ISSUE TITLE
Binaries upload

### ISSUE THREAD

**Issue by Svyatpro** [Joshua-Ashton/dxup#8]
Personally, I couldn't build binaries myself. Meson on Windows doesn't build any dlls for me, I use VS2010.
On Linux I have too many strange errors. Why not just add binaries?

**Comment by axredneck** [comment]
Here are binaries: https://ci.appveyor.com/project/Joshua-Ashton/dxup

**Comment by Svyatpro** [comment]
Maybe I am outdated but where is download link or attached files?
I see only build logs.

**Comment by Svyatpro** [comment]
Thanks for sharing binaries!
Personally, I wanted to try them with current WineD3D. But I didn't manage to make them work.

But meanwhile, I am able to use native Vista, 7, 8 and even latest Win10's d3d10.dll and d3d10_1.dll with current WineD3D build and that brings almost vital D3D10 support. Sure, I use proprietary binaries, but Winetricks and even this project also use proprietary binaries. I'm pretty sure it is possible to make native d3d10 and d3d10_1 dlls work with DXVK and bring proper D3D10 support with lowest performance drop, but it requires to write d3d10core similar to that is in WineD3D. I can even share WineD3D with native d3d10's. Try playing with the d3d10, d3d10_1, d3d10core dlls and DXVK.
[Uploading WineD3D3.8_CSMT_PBA_nativeD3D10_x86.zip…]()

**Comment by Joshua-Ashton** [comment]
There is a setup script included, place your dxvk dlls into that folder with it, call dxvk's dxgi the dxgi_original

**Comment by mirh** [comment]
I'm still not sure why, if the main point is *dxvk*, it wouldn't just be easier to shim/extend that?

**Comment by Joshua-Ashton** [comment]
I can understand this for DX9 and 12. DX10 is literally just DX11 with like 3 functions different and a few extensions on existing ones. It's basically DX10.2. In my eyes there's no reason to implement it that way as it just creates huge code duplication and redundancy.

**Comment by Joshua-Ashton** [comment]
``OpenGL doesn't run on my ZX spectrum. We obviously shouldn't use that.``
Is essentially your argument. Caring for people who haven't upgraded in 6 or so years shouldn't be an interest imho.

**Comment by mirh** [comment]
> DX10 is literally just DX11 with like 3 functions different and a few extensions on existing ones. It's basically DX10.2

That's why it seemed a no brainer to straight down implement it directly into (I'd guess) DXVK. 
But, this is your call then, so whatever.

**Comment by Svyatpro** [comment]
> OpenGL doesn't run on my ZX spectrum. We obviously shouldn't use that.
It is a bad comparison. OpenGL is still in development and really more ubiquitous. It is more common standard.

**Comment by Joshua-Ashton** [comment]
@mirh It'd be messier that way imho, I tried that and I did get it working but it was not nice.

@Svyatpro I still don't get why you are telling me this though, I dont make dxvk

**Comment by Joshua-Ashton** [comment]
You can use dxup with wined3d if you so wish.

**Comment by axredneck** [comment]
> There is a setup script included, place your dxvk dlls into that folder with it, call dxvk's dxgi the dxgi_original

Doesn't work for me, see issue #7

**Comment by Joshua-Ashton** [comment]
Closing this… LMK if you have any issues.
